version: '3'
services:
    php-apache:
        image: php:7.3-apache
        ports:
            - 9030:80
        restart: unless-stopped
        volumes:
            - ./DocumentRoot:/var/www/html

networks:
    default:
        external:
            name: backendmanualnetwork1